kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-replica-pvc
spec:
  storageClassName: openebs-jiva-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
